/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  quide: ["guide/dashboad", "guide/login-join"],
  team: [
    "contributors",
    {
      type: "category",
      label: "쿨피스 Wiki",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "team",
        },
      ],
    },
  ],
};

module.exports = sidebars;
